# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/Users/X4/Documents/GitHub/valjean-nnet/custom_ip/New folder/ip_repo/customip_lab_1.0/hdl/fifo/fifo.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo || ORIG_REF_NAME==fifo}]

# IP: C:/Users/X4/Documents/GitHub/valjean-nnet/custom_ip/New folder/ip_repo/customip_lab_1.0/hdl/fifo/ip/fifo_fifo_generator_0_0/fifo_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_fifo_generator_0_0 || ORIG_REF_NAME==fifo_fifo_generator_0_0}]

# XDC: C:/Users/X4/Documents/GitHub/valjean-nnet/custom_ip/New folder/ip_repo/customip_lab_1.0/hdl/fifo/fifo_ooc.xdc
