# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wmpmiles/courses/comp4601/valjean-nnet/bnn_rtl/bnn_rtl.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
# IP: The module: 'system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wmpmiles/courses/comp4601/valjean-nnet/bnn_rtl/bnn_rtl.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/wmpmiles/courses/comp4601/valjean-nnet/bnn_rtl/bnn_rtl.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
# IP: The module: 'system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wmpmiles/courses/comp4601/valjean-nnet/bnn_rtl/bnn_rtl.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
