webtalk_init -webtalk_dir D:\\Labs\\custom_ip\\custom_ip\\custom_ip.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-04-05 19:26:26" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f9gime2st0cocaepnntlbm9hsm" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.2_8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1554334008508" -context "sdk\\\\hardware/1554334008508"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1554334008508"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1554334008508"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1554334008508"
webtalk_add_data -client sdk -key VivadoVersion -value "2017.2" -context "sdk\\\\hardware/1554334008508"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1554334008508"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1554334008508"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1554334008508"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1554334008508"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1554334008508"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1554334008508"
webtalk_add_data -client sdk -key uid -value "1554334045248" -context "sdk\\\\bsp/1554334045248"
webtalk_add_data -client sdk -key hwid -value "1554334008508" -context "sdk\\\\bsp/1554334045248"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1554334045248"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1554334045248"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1554334045248"
webtalk_add_data -client sdk -key uid -value "1554334100551" -context "sdk\\\\application/1554334100551"
webtalk_add_data -client sdk -key hwid -value "1554334008508" -context "sdk\\\\application/1554334100551"
webtalk_add_data -client sdk -key bspid -value "1554334045248" -context "sdk\\\\application/1554334100551"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1554334100551"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1554334100551"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1554334100551"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1554334100551"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1554334100551"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1554334100551"
webtalk_add_data -client sdk -key projSize -value "162.09375" -context "sdk\\\\application/1554334100551"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1554452786611"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1554452786611"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1554452786611"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1554452786611"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1554452786611"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1554452786611"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1554452786611"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1554452786611"
webtalk_transmit -clientid 982529794 -regid "" -xml D:\\Labs\\custom_ip\\custom_ip\\custom_ip.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\Labs\\custom_ip\\custom_ip\\custom_ip.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\Labs\\custom_ip\\custom_ip\\custom_ip.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
