# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/X4/Documents/GitHub/valjean-nnet/custom_ip/New folder/custom_ip_lab/custom_ip_lab.srcs/sources_1/bd/system/ip/system_customip_lab_0_0/system_customip_lab_0_0.xci
# IP: The module: 'system_customip_lab_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/X4/Documents/GitHub/valjean-nnet/custom_ip/New folder/custom_ip_lab/custom_ip_lab.srcs/sources_1/bd/system/ip/system_customip_lab_0_0/hdl/fifo/ip/fifo_fifo_generator_0_0/fifo_fifo_generator_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_fifo_generator_0_0 || ORIG_REF_NAME==fifo_fifo_generator_0_0}]

# XDC: c:/Users/X4/Documents/GitHub/valjean-nnet/custom_ip/New folder/custom_ip_lab/custom_ip_lab.srcs/sources_1/bd/system/ip/system_customip_lab_0_0/hdl/fifo/ip/fifo_fifo_generator_0_0/fifo_fifo_generator_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_fifo_generator_0_0 || ORIG_REF_NAME==fifo_fifo_generator_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/X4/Documents/GitHub/valjean-nnet/custom_ip/New folder/custom_ip_lab/custom_ip_lab.srcs/sources_1/bd/system/ip/system_customip_lab_0_0/hdl/fifo/fifo_ooc.xdc

# IP: C:/Users/X4/Documents/GitHub/valjean-nnet/custom_ip/New folder/custom_ip_lab/custom_ip_lab.srcs/sources_1/bd/system/ip/system_customip_lab_0_0/system_customip_lab_0_0.xci
# IP: The module: 'system_customip_lab_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/X4/Documents/GitHub/valjean-nnet/custom_ip/New folder/custom_ip_lab/custom_ip_lab.srcs/sources_1/bd/system/ip/system_customip_lab_0_0/hdl/fifo/ip/fifo_fifo_generator_0_0/fifo_fifo_generator_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_fifo_generator_0_0 || ORIG_REF_NAME==fifo_fifo_generator_0_0}]

# XDC: c:/Users/X4/Documents/GitHub/valjean-nnet/custom_ip/New folder/custom_ip_lab/custom_ip_lab.srcs/sources_1/bd/system/ip/system_customip_lab_0_0/hdl/fifo/ip/fifo_fifo_generator_0_0/fifo_fifo_generator_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_fifo_generator_0_0 || ORIG_REF_NAME==fifo_fifo_generator_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/X4/Documents/GitHub/valjean-nnet/custom_ip/New folder/custom_ip_lab/custom_ip_lab.srcs/sources_1/bd/system/ip/system_customip_lab_0_0/hdl/fifo/fifo_ooc.xdc
