# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/cse/cs4601/ip_repo/customip_lab_1.0/hdl/fifo/ip/fifo_fifo_generator_0_0/fifo_fifo_generator_0_0.xci
# IP: The module: 'fifo_fifo_generator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/cse/cs4601/ip_repo/customip_lab_1.0/hdl/fifo/ip/fifo_fifo_generator_0_0/fifo_fifo_generator_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/cse/cs4601/ip_repo/customip_lab_1.0/hdl/fifo/ip/fifo_fifo_generator_0_0/fifo_fifo_generator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/cse/cs4601/ip_repo/customip_lab_1.0/hdl/fifo/ip/fifo_fifo_generator_0_0/fifo_fifo_generator_0_0.xci
# IP: The module: 'fifo_fifo_generator_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/cse/cs4601/ip_repo/customip_lab_1.0/hdl/fifo/ip/fifo_fifo_generator_0_0/fifo_fifo_generator_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/Users/cse/cs4601/ip_repo/customip_lab_1.0/hdl/fifo/ip/fifo_fifo_generator_0_0/fifo_fifo_generator_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_fifo_generator_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
